In [29]:
import numpy as np

In [24]:
#Question 1: 
ar=np.array([i for i in range(2,51,3)])
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [109]:
#Question 2:
l1=[]

for i in range(0,5):
    e=int(input("Enter the elements for first list: "))
    l1.append(e)
l2=[]
for j in range(0,5):
    f=int(input("Enter the elements for second list: "))
    l2.append(f)
arr1=np.array([l1])
arr2=np.array([l2])
print("Concatenated array is: \n",np.concatenate((arr1,arr2)))
print("Sorted araay 1 is: ",np.sort(arr1))
print("Sorted araay 2 is: ",np.sort(arr2))



Enter the elements for first list: 45
Enter the elements for first list: 12
Enter the elements for first list: 78
Enter the elements for first list: 43
Enter the elements for first list: 10
Enter the elements for second list: 0
Enter the elements for second list: 41
Enter the elements for second list: 58
Enter the elements for second list: 11
Enter the elements for second list: 1
Concatenated array is: 
 [[45 12 78 43 10]
 [ 0 41 58 11  1]]
Sorted araay 1 is:  [[10 12 43 45 78]]
Sorted araay 2 is:  [[ 0  1 11 41 58]]


In [37]:
import numpy as np

In [47]:
#Questions 3:
ar=np.array([[23,43,54],[34,5,90]])
print(ar)
print(type(ar))
#dimensions:
print("Dimension is: ",ar.shape)
#size:
print("Size is: ",ar.size)

[[23 43 54]
 [34  5 90]]
<class 'numpy.ndarray'>
Dimension is:  (2, 3)
Size is:  6


In [67]:
#Questions 4:
import numpy as np
ar=np.array([1,2,3,4])
print(ar)
print(ar.shape)
print()
y=np.expand_dims(ar,axis=1)
print(y)
print(y.shape)
print()
z=ar[np.newaxis]
print(z)
print(z.shape)

[1 2 3 4]
(4,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[[1 2 3 4]]
(1, 4)


In [81]:
import numpy as np

In [80]:
#Questions 5:
a=np.array([[2,4,6],[5,4,3],[9,8,0]])
print(a)
b=np.array([[12,34,56],[2,54,7],[7,5,10]])
print(b)
print("Stacking vertically: \n",np.vstack((a,b)))
print("Stacking horizontally: \n",np.hstack((a,b)))

[[2 4 6]
 [5 4 3]
 [9 8 0]]
[[12 34 56]
 [ 2 54  7]
 [ 7  5 10]]
Stacking vertically: 
 [[ 2  4  6]
 [ 5  4  3]
 [ 9  8  0]
 [12 34 56]
 [ 2 54  7]
 [ 7  5 10]]
Stacking horizontally: 
 [[ 2  4  6 12 34 56]
 [ 5  4  3  2 54  7]
 [ 9  8  0  7  5 10]]


In [107]:
#Questions 6:
a=np.array([2,34,23,34,56,77,65,2,23,56])
print("The unique items are: ",np.unique(a))
(unique, counts) = np.unique(a, return_counts=True)
print("frequencies = \n",np.asarray((unique, counts)).T)

The unique items are:  [ 2 23 34 56 65 77]
frequencies = 
 [[ 2  2]
 [23  2]
 [34  2]
 [56  2]
 [65  1]
 [77  1]]
